### ISSUE TITLE
Distinguish Channels ?

### ISSUE THREAD

**Issue by QuentinFchx** [DanielRapp/doppler#1]
Would it be possible to somehow distinguish left/right speakers ?

**Comment by DanielRapp** [comment]
Maybe on laptops. But it'd be impossible for people with flexible (i.e. external) speakers! For obvious reasons :)

**Comment by rafalsobota** [comment]
I don't understand what is impossible. Could you explain? I assume there could be 2 frequencies, one on left, one on right speaker (stereo).

**Comment by DanielRapp** [comment]
There's no good way of defining the "left" and "right" speaker for a computer with external speakers. Just suppose you had two speakers, on to the left and one to the right of the computer. Now suppose you move the right speaker to the left of the computer, and vice versa (this is possible since they're external). The left speaker is now the right speaker and the right speaker is the left speaker!

Although, now that I think about it, perhaps most speakers are labeled "right" and "left"? :)

**Comment by rafalsobota** [comment]
Thanks. I get the point. It may be too strong assumption for every user.

But what if left is on left? Can we then distinguish moving left from moving right?

**Comment by DanielRapp** [comment]
Possibly. To actually triangulate the hand I think you'd also need to know the relative distance between the speakers.
